Update response status codes, fix broken image link in README, add API end-point tests, and add instructions to run API end-point tests
thoth-tech/ChatHistoryDisplayer pull request #12
Opened 2022-12-24 11:14 UTC by rickydodd

This pull request
- Updates the response status codes to be in-line with [this resource](https://restfulapi.net/http-status-codes/).
- Fixes the broken image link in the README.md file.
- Adds API end-point tests (via rspec).
- Adds instructions on how to execute the API end-point tests into the CONTRIBUTING.md file.

2022-12-24 11:56 UTC, lst97 requested changes

2022-12-24 11:56 UTC, lst97 commented on CONTRIBUTING.md
> +rspec spec/api-specs/
show be rspec spec/api_specs/

2022-12-24 15:55 UTC, lst97 submitted a review, later dismissed

2022-12-24 15:56 UTC, lst97 commented
@rickydodd please help me double check my change, I will merge it if you satisfy. Thanks for the work.

2022-12-24 16:36 UTC, lst97 approved these changes

2022-12-25 07:13 UTC, rickydodd commented
Looks good. Functions correctly on manual inputs, passes automatic tests, and the code contributions are good, @lst97. I like the snackbar, it's a good touch and intuitive for a front-end display of errors.

2022-12-25 08:02 UTC, merged